### PR TITLE
Add cancellation support

### PR DESCRIPTION
**Pull request by CollinAlpert**
This PR adds cancellation support to requests.

### CODE REVIEW

**Comment by CollinAlpert** [comment]
Hey, I know this is a large PR, but most of it is just "search and replace". Can I get a status update if this is being reviewed or if there is even interest in adding cancellation support to the APIs?

**Comment by jenschude** [comment]
I have to add it to the code generator as it affects the generated classes

**Comment by CollinAlpert** [comment]
I see. Is the generator part of this repository?

**Comment by jenschude** [comment]
No. I just added your changes to the generator. Plan is to add it to the next release of this SDK

**Comment by jenschude** [comment]
The changes become part of the code generator. Closing it now.

**Comment by CollinAlpert** [comment]
Cool, thanks!

**Comment by jenschude** [comment]
Just merged #196 which adds the cancellation tokens

**Pull request closed without merging**
